---
name: Test

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: ${{ matrix.os }} / Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [Ubuntu]
        python-version: [2.7, 3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@master

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade tox

      - name: Lint with tox
        run: tox -e lint
        if: ${{ startsWith(matrix.python-version,'3') }}

      - name: Test with tox
        run: tox

      - name: Run tox pkg
        run: tox -e pkg
        if: ${{ startsWith(matrix.python-version,'3') }}

      - name: Make docs
        run: tox -e docs
        if: ${{ startsWith(matrix.python-version,'3') }}
